// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: filmclip/v1/filmclip.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Filmclip_CreatePlan_FullMethodName        = "/filmclip.v1.Filmclip/CreatePlan"
	Filmclip_ListPlan_FullMethodName          = "/filmclip.v1.Filmclip/ListPlan"
	Filmclip_QueryPlan_FullMethodName         = "/filmclip.v1.Filmclip/QueryPlan"
	Filmclip_UploadImage_FullMethodName       = "/filmclip.v1.Filmclip/UploadImage"
	Filmclip_ChangeClothing_FullMethodName    = "/filmclip.v1.Filmclip/ChangeClothing"
	Filmclip_GenClipScript_FullMethodName     = "/filmclip.v1.Filmclip/GenClipScript"
	Filmclip_GenClipFirstFrame_FullMethodName = "/filmclip.v1.Filmclip/GenClipFirstFrame"
	Filmclip_GenClipVideo_FullMethodName      = "/filmclip.v1.Filmclip/GenClipVideo"
)

// FilmclipClient is the client API for Filmclip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilmclipClient interface {
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanReply, error)
	ListPlan(ctx context.Context, in *ListPlanRequest, opts ...grpc.CallOption) (*ListPlanReply, error)
	QueryPlan(ctx context.Context, in *QueryPlanRequest, opts ...grpc.CallOption) (*QueryPlanReply, error)
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageReply, error)
	ChangeClothing(ctx context.Context, in *ChangeClothingRequest, opts ...grpc.CallOption) (*ChangeClothingReply, error)
	GenClipScript(ctx context.Context, in *GenClipScriptRequest, opts ...grpc.CallOption) (*GenClipScriptReply, error)
	GenClipFirstFrame(ctx context.Context, in *GenClipFrameRequest, opts ...grpc.CallOption) (*GenClipFrameReply, error)
	GenClipVideo(ctx context.Context, in *GenClipVideoRequest, opts ...grpc.CallOption) (*GenClipVideoReply, error)
}

type filmclipClient struct {
	cc grpc.ClientConnInterface
}

func NewFilmclipClient(cc grpc.ClientConnInterface) FilmclipClient {
	return &filmclipClient{cc}
}

func (c *filmclipClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*CreatePlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanReply)
	err := c.cc.Invoke(ctx, Filmclip_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) ListPlan(ctx context.Context, in *ListPlanRequest, opts ...grpc.CallOption) (*ListPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlanReply)
	err := c.cc.Invoke(ctx, Filmclip_ListPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) QueryPlan(ctx context.Context, in *QueryPlanRequest, opts ...grpc.CallOption) (*QueryPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPlanReply)
	err := c.cc.Invoke(ctx, Filmclip_QueryPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadImageReply)
	err := c.cc.Invoke(ctx, Filmclip_UploadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) ChangeClothing(ctx context.Context, in *ChangeClothingRequest, opts ...grpc.CallOption) (*ChangeClothingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeClothingReply)
	err := c.cc.Invoke(ctx, Filmclip_ChangeClothing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) GenClipScript(ctx context.Context, in *GenClipScriptRequest, opts ...grpc.CallOption) (*GenClipScriptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenClipScriptReply)
	err := c.cc.Invoke(ctx, Filmclip_GenClipScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) GenClipFirstFrame(ctx context.Context, in *GenClipFrameRequest, opts ...grpc.CallOption) (*GenClipFrameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenClipFrameReply)
	err := c.cc.Invoke(ctx, Filmclip_GenClipFirstFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmclipClient) GenClipVideo(ctx context.Context, in *GenClipVideoRequest, opts ...grpc.CallOption) (*GenClipVideoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenClipVideoReply)
	err := c.cc.Invoke(ctx, Filmclip_GenClipVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilmclipServer is the server API for Filmclip service.
// All implementations must embed UnimplementedFilmclipServer
// for forward compatibility.
type FilmclipServer interface {
	CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanReply, error)
	ListPlan(context.Context, *ListPlanRequest) (*ListPlanReply, error)
	QueryPlan(context.Context, *QueryPlanRequest) (*QueryPlanReply, error)
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageReply, error)
	ChangeClothing(context.Context, *ChangeClothingRequest) (*ChangeClothingReply, error)
	GenClipScript(context.Context, *GenClipScriptRequest) (*GenClipScriptReply, error)
	GenClipFirstFrame(context.Context, *GenClipFrameRequest) (*GenClipFrameReply, error)
	GenClipVideo(context.Context, *GenClipVideoRequest) (*GenClipVideoReply, error)
	mustEmbedUnimplementedFilmclipServer()
}

// UnimplementedFilmclipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilmclipServer struct{}

func (UnimplementedFilmclipServer) CreatePlan(context.Context, *CreatePlanRequest) (*CreatePlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedFilmclipServer) ListPlan(context.Context, *ListPlanRequest) (*ListPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlan not implemented")
}
func (UnimplementedFilmclipServer) QueryPlan(context.Context, *QueryPlanRequest) (*QueryPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPlan not implemented")
}
func (UnimplementedFilmclipServer) UploadImage(context.Context, *UploadImageRequest) (*UploadImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedFilmclipServer) ChangeClothing(context.Context, *ChangeClothingRequest) (*ChangeClothingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeClothing not implemented")
}
func (UnimplementedFilmclipServer) GenClipScript(context.Context, *GenClipScriptRequest) (*GenClipScriptReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenClipScript not implemented")
}
func (UnimplementedFilmclipServer) GenClipFirstFrame(context.Context, *GenClipFrameRequest) (*GenClipFrameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenClipFirstFrame not implemented")
}
func (UnimplementedFilmclipServer) GenClipVideo(context.Context, *GenClipVideoRequest) (*GenClipVideoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenClipVideo not implemented")
}
func (UnimplementedFilmclipServer) mustEmbedUnimplementedFilmclipServer() {}
func (UnimplementedFilmclipServer) testEmbeddedByValue()                  {}

// UnsafeFilmclipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilmclipServer will
// result in compilation errors.
type UnsafeFilmclipServer interface {
	mustEmbedUnimplementedFilmclipServer()
}

func RegisterFilmclipServer(s grpc.ServiceRegistrar, srv FilmclipServer) {
	// If the following call pancis, it indicates UnimplementedFilmclipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Filmclip_ServiceDesc, srv)
}

func _Filmclip_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_ListPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).ListPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_ListPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).ListPlan(ctx, req.(*ListPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_QueryPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).QueryPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_QueryPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).QueryPlan(ctx, req.(*QueryPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_UploadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_ChangeClothing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeClothingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).ChangeClothing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_ChangeClothing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).ChangeClothing(ctx, req.(*ChangeClothingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_GenClipScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenClipScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).GenClipScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_GenClipScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).GenClipScript(ctx, req.(*GenClipScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_GenClipFirstFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenClipFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).GenClipFirstFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_GenClipFirstFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).GenClipFirstFrame(ctx, req.(*GenClipFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filmclip_GenClipVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenClipVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmclipServer).GenClipVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filmclip_GenClipVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmclipServer).GenClipVideo(ctx, req.(*GenClipVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Filmclip_ServiceDesc is the grpc.ServiceDesc for Filmclip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Filmclip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filmclip.v1.Filmclip",
	HandlerType: (*FilmclipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlan",
			Handler:    _Filmclip_CreatePlan_Handler,
		},
		{
			MethodName: "ListPlan",
			Handler:    _Filmclip_ListPlan_Handler,
		},
		{
			MethodName: "QueryPlan",
			Handler:    _Filmclip_QueryPlan_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _Filmclip_UploadImage_Handler,
		},
		{
			MethodName: "ChangeClothing",
			Handler:    _Filmclip_ChangeClothing_Handler,
		},
		{
			MethodName: "GenClipScript",
			Handler:    _Filmclip_GenClipScript_Handler,
		},
		{
			MethodName: "GenClipFirstFrame",
			Handler:    _Filmclip_GenClipFirstFrame_Handler,
		},
		{
			MethodName: "GenClipVideo",
			Handler:    _Filmclip_GenClipVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filmclip/v1/filmclip.proto",
}
